pizzamama/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),    # Pour déterminer la vue du chemin url 'menu', dans le fichier views.py
]

pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),    # Pour déterminer la vue du chemin url 'menu', dans le fichier views.py
]

pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),    # Dans l'url si je tape /menu, il va aller chercher le fichier urls.py dans l'app 'menu'
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

pizzamama/main/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):      # Pour afficher les objets par leur nom dans la partie admin
        return self.name

pizzamama/menu/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):      # Pour afficher les objets par leur nom dans la partie admin
        return self.name

pizzamama/main/views.py
from django.shortcuts import render     # Permet d'aller chercher un template


def index(request):
    return render(request, 'main/index.html')

pizzamama/menu/views.py
from django.shortcuts import render     # Permet d'aller chercher un template
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza

# Create your views here.
def index(request):
    # pizzas = Pizza.objects.all()                                                                    # Je récupère l'objet Pizza de la bdd avec ses informations
    # pizzas_names_and_prices = [pizza.name + " : " + str(pizza.price) + "€" for pizza in pizzas]     # Je stocke les noms et prix des pizzas dans une liste
    # pizzas_names_and_prices_str = ", ".join(pizzas_names_and_prices)                                # Je transforme en chaine de caractères
    # return HttpResponse("Les pizzas : " + pizzas_names_and_prices_str)                              # Ce qui sera affiché à l'écran au chemin url 'menu'

    pizzas = Pizza.objects.all().order_by('price')                  # Je passe tout l'objet Pizza
    return render(request, 'menu/index.html', {'pizzas': pizzas})   # Appel de mon rendu index.html, définition de la clé 'pizzas' pour passer les données au rendu

def api_get_pizzas(request):
    pizzas = Pizza.objects.all()                                    # Dans 'pizzas' j'ai une liste d'objets de type Pizza
    json = serializers.serialize("json", pizzas)                    # Je serialize au format json 'pizzas'
    return HttpResponse(json)

pizzamama/main/templates/main/index.html
<!-- Pour charger un fichier dans le dossier 'static' -->
{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>PizzaMama</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Pour charger ma feuille de style dans le dossier 'static' -->
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
</head>
<body>
    <div class="centered">
        <img src="{% static 'main/images/main_logo.png' %}" alt="logo">
        <a href="{% url 'menu:index' %}">Voir le menu</a>   <!-- Pour préciser le chemin j'utilise le 'namespace' définit dans urls.py -->
    </div>
</body>
</html>

pizzamama/menu/templates/menu/index.html
<!-- Pour charger un fichier dans le dossier 'static' -->
{% load static %}
<!-- TAILWIND -->
{% load tailwind_tags %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Menu des pizzas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Pour charger ma feuille de style dans le dossier 'static' -->
    <!-- <link rel="stylesheet" href="{% static 'menu/style.css' %}"> -->
    <!-- TAILWIND -->
    {% tailwind_css %}
</head>
<body style="background-image: url('/static/menu/images/menu_background.jpg');" class="bg-no-repeat bg-cover bg-center bg-fixed font-arial">
<!--    <div class="my-6 mx-6 text-white w-auto sm:w-96">-->
    <div class="w-screen bg-black bg-opacity-30">
        <div class="m-0 p-8 sm:p-12 md:p-16 lg:pl-32 text-white max-w-3xl">
            <div class="">
                <a href="{% url 'main:index' %}">
                    <img src="{% static 'menu/images/small_logo.png' %}" alt="logo">
                </a>
            </div>

            <div class="mt-6">
                <h1 class="text-2xl font-bold rounded-lg bg-orange-500 px-5 py-2 w-fit">Les Pizzas</h1>
            </div>

            <div class="mt-6">
                <!-- Je boucle sur toutes les pizzas pour récupérer les informations de chaque pizza et accéder par exemple à leur nom -->
                {% for pizza in pizzas %}
                    <div class="mb-4">
                        <div class="flex justify-between">
                            <div class="text-xl font-bold">{{pizza.name}}</div>
                            <div class="text-orange-500 rounded-full bg-black bg-opacity-70 px-2 py-1">{{pizza.price | floatformat:2}}€</div>   <!-- Gestion du format du prix -->
                        </div>

                        <div class="mt-1 text-gray-200">{{pizza.ingredients | title}}</div>
                        {% if pizza.vegetarian %}
                            <div class="mt-3"><span class="text-sm text-black rounded-full bg-orange-500 px-2 py-1">Végétarienne</span></div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</body>
</html>

pizzamama/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>